project:
  type: website

website:
  title: "ykstats.github.io"
  page-navigation: true
  sidebar:
    search: true
    contents: 
      - text: StatsCentral
        href: index.qmd
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
warning: false
editor: visual

