project:
  type: website

website:
  title: "github.io"
  page-navigation: true
  sidebar:
    search: true
    contents: 
      - text: StatsCentral
        href: index.qmd
      - text: MathStats2
        href: mathstats2.qmd
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

